# Generated by Django 5.0.6 on 2024-08-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('ready_for_pickup', 'Ready for Pickup'), ('ready_for_shipping', 'Ready for Shipping'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='preparing', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('pickup', 'Pick up at store'), ('shipping', 'Shipping')], max_length=10),
        ),
    ]
