# Generated by Django 5.0.6 on 2024-08-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommerceitem',
            name='is_returnable',
            field=models.BooleanField(default=True),
        ),
    ]
