# Generated by Django 5.0.6 on 2024-08-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('preparing', 'Preparing'), ('ready_for_pickup', 'Ready for Pickup'), ('ready_for_shipping', 'Ready for Shipping'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('complete', 'Complete')], default='unread', max_length=20),
        ),
    ]
