# Generated by Django 5.0.6 on 2024-08-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='denied_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('received', 'Received'), ('waiting_for_payment', 'Waiting for Payment'), ('complete', 'Complete')], default='pending', max_length=20),
        ),
    ]
