# Generated by Django 5.0.6 on 2024-08-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_returnrequest_refund_amount_returnrequest_refund_hst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='refund_hst',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='refund_subtotal',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='restocking_fee',
        ),
    ]
