# Generated by Django 5.0.6 on 2024-09-06 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_returnrequest_refund_hst_and_more'),
        ('oauth_handler', '0009_item_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_handler.item'),
        ),
    ]
