# Generated by Django 5.1.2 on 2024-10-27 14:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_alter_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_with_hst_and_shipping',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
