# Generated by Django 5.1.3 on 2024-12-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_orderitem_packed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='back_order_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='packed_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
