# Generated by Django 5.1.3 on 2024-12-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_orderitem_back_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_sale_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
