# Generated by Django 5.0.6 on 2024-07-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_handler', '0002_brand_status_category_status_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='min_order_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
