# Generated by Django 5.0.6 on 2024-08-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_handler', '0003_item_min_order_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='CustomerLightspeed',
        ),
    ]
