# Generated by Django 5.0.6 on 2024-08-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_handler', '0005_item_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_returnable',
            field=models.BooleanField(default=True),
        ),
    ]
