# Generated by Django 5.0.6 on 2024-09-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_handler', '0006_item_is_returnable'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bag_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='bag_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='box_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='box_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
