# Generated by Django 5.0.6 on 2024-09-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_handler', '0007_item_bag_discount_percentage_item_bag_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='has_bag_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='has_box_option',
            field=models.BooleanField(default=False),
        ),
    ]
