# Generated by Django 5.0.6 on 2024-09-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_handler', '0008_item_has_bag_option_item_has_box_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
