# Generated by Django 5.1.2 on 2024-10-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_handler', '0011_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in inches', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in inches', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in inches', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Weight in pounds (lbs)', max_digits=5),
        ),
    ]
