# Generated by Django 5.1.2 on 2024-11-05 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_handler', '0012_item_height_item_length_item_width_alter_item_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCategoryMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.DecimalField(decimal_places=2, help_text='Multiplier for price calculation', max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_handler.category')),
            ],
        ),
    ]
