# Generated by Django 5.1.2 on 2024-11-05 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_handler', '0013_pricecategorymultiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_category_multiplier',
            field=models.ForeignKey(blank=True, help_text='Choose price category multiplier for automatic price calculation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='oauth_handler.pricecategorymultiplier'),
        ),
    ]
